// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjT-PYE1h-iZYgbLsMYLDKnM9s6VGjlx4',
    appId: '1:827436824005:web:f145bfd73ccdf86eddc7ac',
    messagingSenderId: '827436824005',
    projectId: 'flutter-dc61b',
    authDomain: 'flutter-dc61b.firebaseapp.com',
    storageBucket: 'flutter-dc61b.firebasestorage.app',
    measurementId: 'G-XY1GDC50WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI2J_Pnl5FBQR9TwXsSKwj23VLff2Py30',
    appId: '1:827436824005:android:4b8d239cf099a683ddc7ac',
    messagingSenderId: '827436824005',
    projectId: 'flutter-dc61b',
    storageBucket: 'flutter-dc61b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwNKQ6tKdKq9IMStuJy3ReHIdE_GQ-KiQ',
    appId: '1:827436824005:ios:c9d06620f764d2b3ddc7ac',
    messagingSenderId: '827436824005',
    projectId: 'flutter-dc61b',
    storageBucket: 'flutter-dc61b.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwNKQ6tKdKq9IMStuJy3ReHIdE_GQ-KiQ',
    appId: '1:827436824005:ios:c9d06620f764d2b3ddc7ac',
    messagingSenderId: '827436824005',
    projectId: 'flutter-dc61b',
    storageBucket: 'flutter-dc61b.firebasestorage.app',
    iosBundleId: 'com.example.newApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjT-PYE1h-iZYgbLsMYLDKnM9s6VGjlx4',
    appId: '1:827436824005:web:d6be30e39c738616ddc7ac',
    messagingSenderId: '827436824005',
    projectId: 'flutter-dc61b',
    authDomain: 'flutter-dc61b.firebaseapp.com',
    storageBucket: 'flutter-dc61b.firebasestorage.app',
    measurementId: 'G-22FME3XP76',
  );
}
